baseURL: /
languageCode: en-us
title: Zachary Groton
theme: personal-web
copyright: © Zachary Groton
googleAnalytics: ''
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
params:
  accentColor: '#FD3519'
  assets:
    customCSS: ''
    favicon: ''
  breadcrumb: yes
  contact:
    email: 'ztgroton@gmail.com'
    text: ''
  intro:
    main: 'Zachary Groton'
    sub: 'Data Scientist & App Developer'
  main: 
    latestPublishHeader: ' '
  mainSections: []
  notFound:
    gopher: /images/gopher.png
    h1: Bummer!
    p: 'It seems that this page doesn''t exist.'
  rendererSafe: no
  sections:
    portfolio: project
  sidebar:
    backgroundImage: ''
    gradientOverlay: ''
    logo: '/images/profile_pic.png'
  social:
    linkedin: https://www.linkedin.com/in/zachary-groton
taxonomies:
  design: designs
  tech: techs
blackfriday:
  hrefTargetBlank: yes
menu:
  main:
    - identifier: about
      name: About Me
      title: About
      url: /about/
      weight: -120
    - identifier: portfolio
      name: Project Portfolio
      title: Portfolio
      url: /portfolio/
      weight: -110
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
privacy:
  googleAnalytics:
    anonymizeIP: yes
    disable: yes
    respectDoNotTrack: yes
    useSessionStorage: no
  twitter:
    disable: no
    enableDNT: yes
    simple: no
markup:
  goldmark:
    renderer:
      unsafe: yes
